QRADAR_GROUPS = {
    'SBERDEVICE SBERDEVICE-INFRA': 'SBERDEVICE-INFRA',
    'SBERCLOUD SBERCLOUD-INFRA': 'SBERCLOUD-INFRA',
    'BIZONE BZ-INFRA': 'BZ-INFRA',
    'URLC URLC-INFRA': 'URLC-INFRA',
    'DEV DEV-INFRA': 'DEV-INFRA',
    'SBAST SBAST-INFRA': 'SBAST-INFRA',
    'RTS RTS-INFRA': 'RTS-INFRA',
    'INTERFAX INTERFAX-INFRA': 'INTERFAX-INFRA',
    'AFL AFL-SITE': 'AFL-SITE',
    'AFL AFL-INFRA': 'AFL-INFRA',
    'URALKALI URALKALI-INFRA': 'URALKALI-INFRA',
    'RAMBLER RAMBLER-INFRA': 'RAMBLER-INFRA',
    'UNICREDIT UNICREDIT-INFRA': 'UNICREDIT-INFRA'
}
